pipeline {
    agent any

    stages {

        stage('Clone') {
            steps {
                git 'https://github.com/Apurva-Solanke/smartshop-devops-project.git'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean package'
                sh 'mvn -f product-service/pom.xml clean package'
                sh 'mvn -f order-service/pom.xml clean package'
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t user-service ./user-service'
                sh 'docker build -t product-service ./product-service'
                sh 'docker build -t order-service ./order-service'
            }
        }

        stage('Deploy to K8s') {
            steps {
                sh 'kubectl apply -f k8s/'
            }
        }
    }
}